import type React from "react"
import type { Metadata, Viewport } from "next"
import { cookies } from "next/headers"
import { Geist } from "next/font/google"
import "./globals.css"
import { LanguageProvider } from "../lib/language-context"
import HtmlLang from "../components/HtmlLang"

const geist = Geist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist",
})

const SITE_URL = "https://facundozin.vercel.app"
const DESCRIPTION =
  "AI Native Software Engineer specializing in scalable systems, LLM integration, and enterprise applications. C#, .NET, TypeScript, NestJS, React."

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: "Facundo Zin - Software Engineer",
  description: DESCRIPTION,
  keywords: [
    "Facundo Zin",
    "Software Engineer",
    "AI Native",
    "LLM integration",
    "C#",
    ".NET",
    "TypeScript",
    "NestJS",
    "React",
    "Docker",
  ],
  authors: [{ name: "Facundo Zin", url: SITE_URL }],
  creator: "Facundo Zin",
  publisher: "Facundo Zin",
  alternates: {
    canonical: "/",
  },
  // Social preview images are generated by app/opengraph-image.tsx and
  // app/twitter-image.tsx (PNG). SVG is intentionally NOT used here because
  // most social platforms refuse to render SVG og:images.
  openGraph: {
    title: "Facundo Zin - Software Engineer",
    description: DESCRIPTION,
    url: SITE_URL,
    siteName: "Facundo Zin Portfolio",
    locale: "es_AR",
    alternateLocale: ["en_US"],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Facundo Zin - Software Engineer",
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
  },
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    // The apple touch icon is generated by app/apple-icon.tsx. It must be
    // referenced explicitly because Next.js drops file-convention icon
    // metadata whenever `metadata.icons` is already configured.
    apple: "/apple-icon",
  },
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
}

// Applies the persisted theme before first paint to avoid a flash of the
// default (dark) theme. Kept tiny and defensive.
const THEME_INIT_SCRIPT = `(function(){try{var t=localStorage.getItem("theme");document.documentElement.classList.toggle("dark",t!=="light");}catch(e){}})();`

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const locale = (cookieStore.get("locale")?.value as "es" | "en") || "es"

  return (
    <html lang={locale} className={`${geist.variable}`} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
        <link rel="preconnect" href="https://githubstats-livid.vercel.app" />
        <link rel="preconnect" href="https://cdn.jsdelivr.net" crossOrigin="anonymous" />
        <link rel="dns-prefetch" href="https://githubstats-livid.vercel.app" />
        <link rel="dns-prefetch" href="https://cdn.jsdelivr.net" />
      </head>
      <body className="font-sans antialiased">
        <LanguageProvider initialLocale={locale}>
          <HtmlLang />
          {children}
        </LanguageProvider>
      </body>
    </html>
  )
}
